"""Generate CLAUDE.md from analysis results."""
from __future__ import annotations

from pathlib import Path

from cca.parser import FileInfo

CLAUDEIGNORE_PATTERNS = [
    "__pycache__/",
    "*.pyc",
    ".venv/",
    "venv/",
    ".git/",
    "*.egg-info/",
    "dist/",
    "build/",
    ".pytest_cache/",
    ".mypy_cache/",
    "*.log",
    "*.lock",
]


def _structure_tree(root: Path, file_infos: list[FileInfo]) -> str:
    seen: set[str] = set()
    lines: list[str] = []
    for info in sorted(file_infos, key=lambda f: f.path):
        rel = info.path.relative_to(root)
        for i in range(1, len(rel.parts)):
            key = str(Path(*rel.parts[:i]))
            if key not in seen:
                seen.add(key)
                depth = i - 1
                lines.append("  " * depth + rel.parts[i - 1] + "/")
    return "\n".join(lines) or "(flat project)"


def generate_claude_md(
    root: Path,
    file_infos: list[FileInfo],
    most_imported: list[tuple[str, int]],
    hot_files: dict[str, int],
    unused_exports: dict[str, list[str]],
    token_savings_pct: float | None = None,
    frameworks: dict[str, str] | None = None,
) -> str:
    total_lines = sum(f.lines for f in file_infos)
    total_funcs = sum(f.function_count for f in file_infos)
    total_classes = sum(f.class_count for f in file_infos)
    total_typed = sum(f.typed_functions for f in file_infos)
    type_cov = total_typed / total_funcs * 100 if total_funcs else 0.0
    avg_complexity = (
        sum(f.complexity for f in file_infos) / len(file_infos) if file_infos else 0
    )

    sections: list[str] = [
        "# CLAUDE.md",
        "",
        "> Auto-generated by [claude-context-analyzer](https://github.com/yourusername/claude-context-analyzer).",
        "> Review and edit before committing.",
        "",
        "## Project Overview",
        "",
        f"- **Files:** {len(file_infos)} Python files",
        f"- **Lines of code:** {total_lines:,}",
        f"- **Functions:** {total_funcs}  |  **Classes:** {total_classes}",
        f"- **Type coverage:** {type_cov:.0f}%  |  **Avg complexity:** {avg_complexity:.1f}",
    ]
    if token_savings_pct is not None:
        sections.append(f"- **Estimated token reduction with .claudeignore:** {token_savings_pct:.1f}%")

    if frameworks:
        fw_list = ", ".join(frameworks.values())
        sections.append(f"- **Detected frameworks:** {fw_list}")

    sections += [
        "",
        "## Project Structure",
        "",
        "```",
        _structure_tree(root, file_infos),
        "```",
        "",
    ]

    core = [(p, c) for p, c in most_imported if c > 0]
    if core:
        sections += [
            "## Core Files (High Dependency Impact)",
            "",
            "Changes here affect many other modules - review carefully:",
            "",
            "| File | Imported by |",
            "|------|-------------|",
        ]
        for path, count in core[:8]:
            sections.append(f"| `{path}` | {count} file{'s' if count != 1 else ''} |")
        sections.append("")

    if hot_files:
        sections += [
            "## Hot Files (Change Frequently)",
            "",
            "Based on recent git history:",
            "",
            "| File | Changes |",
            "|------|---------|",
        ]
        for path, count in sorted(hot_files.items(), key=lambda x: x[1], reverse=True)[:8]:
            sections.append(f"| `{path}` | {count} |")
        sections.append("")

    if unused_exports:
        sections += [
            "## Possible Dead Code",
            "",
            "> Defined but never imported elsewhere. Verify before removing - ",
            "> dynamic access or `__all__` usage may not be detected.",
            "",
        ]
        for path, syms in list(unused_exports.items())[:10]:
            sections.append(f"- **`{path}`**: {', '.join(f'`{s}`' for s in syms)}")
        sections.append("")

    if (root / "DECISIONS.md").exists():
        sections += [
            "## Architecture Decisions",
            "",
            "> See [DECISIONS.md](DECISIONS.md) for WHY the code is structured this way.",
            "> Read it before making structural changes.",
            "",
        ]

    sections += [
        "## Recommended .claudeignore",
        "",
        "```",
        *CLAUDEIGNORE_PATTERNS,
        "```",
        "",
    ]

    return "\n".join(sections)
