"""Context snapshot generator.

Compresses an entire project into a single CONTEXT.md that Claude can read
instead of loading every source file. Typical reduction: 50K tokens → 2-4K tokens.

The snapshot contains:
  - Filtered file tree (respects .claudeignore)
  - Function/class signatures per file (no bodies)
  - Import relationships summary
  - Token budget before/after
"""
from __future__ import annotations

import re
from pathlib import Path

from cca.token_counter import (
    _is_binary,
    _is_ignored,
    _parse_claudeignore,
    count_tokens,
    CLAUDEIGNORE_DIRS,
)


def _build_file_tree(root: Path, ci_patterns: list[str]) -> list[str]:
    """Return sorted list of project-relative paths, claudeignore applied."""
    paths = []
    for f in sorted(root.rglob("*")):
        if not f.is_file() or _is_binary(f):
            continue
        rel = str(f.relative_to(root))
        if ci_patterns:
            if _is_ignored(rel, ci_patterns):
                continue
        else:
            if any(part in CLAUDEIGNORE_DIRS for part in f.parts):
                continue
            if any(part.endswith(".egg-info") for part in f.parts):
                continue
        paths.append(rel.replace("\\", "/"))
    return paths


def _tree_lines(paths: list[str]) -> list[str]:
    """Convert flat path list to indented tree lines."""
    lines: list[str] = []
    seen_dirs: set[str] = set()
    for p in sorted(paths):
        parts = p.split("/")
        for depth, part in enumerate(parts[:-1]):
            prefix = "/".join(parts[:depth + 1])
            if prefix not in seen_dirs:
                seen_dirs.add(prefix)
                lines.append("  " * depth + f"  {part}/")
        depth = len(parts) - 1
        lines.append("  " * depth + f"  {parts[-1]}")
    return lines


def _extract_signatures(source: str) -> list[str]:
    """Extract def/class lines from Python source (signatures only, no bodies)."""
    sigs: list[str] = []
    for line in source.splitlines():
        stripped = line.lstrip()
        if stripped.startswith(("def ", "async def ", "class ")):
            indent = len(line) - len(stripped)
            sig = stripped.rstrip(":").rstrip()
            # Remove body-less class definitions and keep clean
            sig = re.sub(r"\s+", " ", sig)
            sigs.append("  " * (indent // 4) + sig)
    return sigs


def build_snapshot(root: Path) -> str:
    """Generate a markdown snapshot of *root*.

    Returns the full markdown string. Caller decides where to write it.
    """
    ci_patterns = _parse_claudeignore(root)
    all_files = _build_file_tree(root, ci_patterns)

    project_name = root.resolve().name or root.resolve().stem or "project"
    lines: list[str] = [
        f"# Project Snapshot — {project_name}",
        "",
        "> Auto-generated by `tslayer snapshot`. "
        "Read this file instead of individual source files.",
        "",
        "## File Tree",
        "```",
    ]
    lines += _tree_lines(all_files)
    lines += ["```", ""]

    # Signatures section — only Python files
    py_files = [p for p in all_files if p.endswith(".py")]
    if py_files:
        lines += ["## Signatures", ""]
        for rel in sorted(py_files):
            fpath = root / rel.replace("/", "\\")
            try:
                src = fpath.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue
            sigs = _extract_signatures(src)
            if not sigs:
                continue
            lines.append(f"### `{rel}`")
            lines.append("```python")
            lines += sigs
            lines.append("```")
            lines.append("")

    # Configuration / documentation files — show full content if small
    doc_exts = {".md", ".toml", ".cfg", ".ini", ".env", ".yml", ".yaml"}
    small_docs = [
        p for p in all_files
        if any(p.endswith(ext) for ext in doc_exts)
        and (root / p.replace("/", "\\")).stat().st_size < 4_096
    ]
    if small_docs:
        lines += ["## Config & Docs", ""]
        for rel in sorted(small_docs):
            fpath = root / rel.replace("/", "\\")
            try:
                content = fpath.read_text(encoding="utf-8", errors="ignore").strip()
            except Exception:
                continue
            ext = rel.rsplit(".", 1)[-1]
            lines.append(f"### `{rel}`")
            lines.append(f"```{ext}")
            lines.append(content)
            lines.append("```")
            lines.append("")

    return "\n".join(lines)


def snapshot_token_stats(root: Path, snapshot_text: str) -> dict:
    """Compare snapshot tokens vs claudeignore-filtered project tokens."""
    from cca.token_counter import count_project_tokens
    optimized = count_project_tokens(root)["total"]
    snap_tokens = count_tokens(snapshot_text)
    return {
        "with_claudeignore_tokens": optimized,
        "snapshot_tokens": snap_tokens,
        "reduction_pct": round((1 - snap_tokens / optimized) * 100, 1) if optimized else 0.0,
    }
